name: Run .NET API Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET 9.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore WebApplication1/WebApplication1.sln

      - name: Build project
        run: dotnet build WebApplication1/WebApplication1.sln --configuration Debug --no-restore

    
      - name: Run API in background
        run: |
          nohup dotnet WebApplication1/WebApplication1/bin/Debug/net9.0/WebApplication1.dll \
            --urls "http://0.0.0.0:5105" > api.log 2>&1 &
          sleep 15

   
      - name: Show API Logs
        run: cat api.log

      - name: Wait for API to be ready
        run: npx wait-on http://localhost:5105 --timeout 120000

      
      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman Tests and Save Report
        run: |
          mkdir -p reports
          newman run WebApplication1/docs/api/postman_collection.json \
            --delay-request 1000 \
            --reporters cli,html \
            --reporter-html-export reports/test-report.html

      - name: Upload Newman Report
        uses: actions/upload-artifact@v4
        with:
          name: postman-report
          path: reports/test-report.html
